[package]
name = "sosd"
description = "Amazing soft OSD for linux"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.dev]
opt-level = 1
incremental = true

[profile.release]
strip = true
lto = "thin"
panic = 'abort'
opt-level = 3
codegen-units = 1

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
cosmic-text = "0.12.1"
raqote = { version = "0.8.5", default-features = false }
serde = { version = "1.0.214", features = ["derive"] }
smithay-client-toolkit = "0.19.2"
tokio = { version = "1.42.0", default-features = false, features = ["macros", "rt-multi-thread"] }
wayland-client = "0.31.7"
zbus = { version = "5.1.0", default-features = false, features = ["tokio"] }
