allow-branch = ["main", "dev", "!HEAD"]
publish = false
pre-release-commit-message = "chore: Release simplemoji version {{version}}"
tag-message = "chore: Release simplemoji version {{version}}"
tag-name = "v{{version}}"
