[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
directories = "5.0.1"
merge2 = "0.3.0"
serde = { version = "1.0.214", features = ["derive"] }
toml = "0.8.19"
