[package]
name = "services"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
config = { version = "0.1.0", path = "../config" }
image.workspace = true
parking_lot.workspace = true
serde.workspace = true
tokio.workspace = true
zbus.workspace = true
